import { Router } from 'express';
import { asyncHandler } from '../utils/http';
import * as p from '../controllers/public';
import * as a from '../controllers/auth';
import * as ad from '../controllers/admin';
import { requireAuth } from '../middleware/auth';

const r=Router();
r.get('/health',asyncHandler(p.health));
r.get('/events',asyncHandler(p.getEvents));
r.get('/events/featured',asyncHandler(p.getFeatured));
r.get('/events/cultural',asyncHandler(async(req,res)=>{req.query.category='Cultural';return p.getEvents(req,res)}));
r.get('/events/sports',asyncHandler(async(req,res)=>{req.query.category='Sports';return p.getEvents(req,res)}));
r.get('/events/:id',asyncHandler(p.getEvent));
r.get('/announcements',asyncHandler(p.getAnnouncements));
r.get('/announcements/latest',asyncHandler(p.getAnnouncements));
r.get('/results',asyncHandler(p.getResults));
r.get('/results/latest',asyncHandler(p.getResults));
r.get('/schedule',asyncHandler(p.getSchedule));
r.get('/sponsors',asyncHandler(p.getSponsors));
r.get('/gallery',asyncHandler(p.getGallery));
r.post('/contact',asyncHandler(p.createContact));
r.post('/registrations',asyncHandler(p.createRegistration));
r.post('/auth/login',asyncHandler(a.login));
r.get('/auth/me',requireAuth,asyncHandler(a.me));

const admin=Router();
admin.use(requireAuth);
admin.get('/dashboard',asyncHandler(ad.dashboard));
admin.get('/registrations',asyncHandler(ad.registrations));
admin.get('/registrations/export',asyncHandler(ad.exportRegistrations));
admin.get('/registrations/:id',asyncHandler(ad.registrationById));
admin.put('/registrations/:id/status',asyncHandler(ad.updateRegistrationStatus));
admin.get('/:resource',asyncHandler(ad.listResource));
admin.post('/:resource',asyncHandler(ad.createResource));
admin.put('/:resource/:id',asyncHandler(ad.updateResource));
admin.delete('/:resource/:id',asyncHandler(ad.deleteResource));
r.use('/admin',admin);
export default r;
